name: cicd

on: push

jobs:
  Test:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run Python
      run: python ./python-hello.py
  Build:
    name: Second job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-artifact
        path: ./python-hello.py
    
