name: cicd

on: push

jobs:
  Test:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v1.1.1
    - name: Run Python
      run: ./python python-hello.py
